### ISSUE TITLE
Clarify response/survey relationship

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-docs#15]
There is a 1:1 relationship between these and our glossary isn't currently very clear. Is there anything else in our glossary we can clarify? I feel the definition of "response" as a "completed survey" is maybe not great. It doesn't have to be completed.

**Comment by rmarow** [comment]
Done here: 91c83862aa9288c9f47c407c0292486baa66f11d and 2c8b4b127edd64dadc8cf882f6c101b931fc01fa
