### ISSUE TITLE
Create Relationship section in glossary

### ISSUE THREAD

**Issue by rmarow** [nsidc/usaon-vta-docs#18]
- Define sequential order of relationships 
- attributes of each relationship (are they all the same)

**Comment by rmarow** [comment]
@hazelshapiro a flowchart would be fine for this too

**Comment by hazelshapiro** [comment]
Sequential order is defined by objects on the left side of the diagram "supporting" objects further right. 

`Societal benefit areas` are supported by `Applications`.

`Applications` are supported by `Data products` or, rarely, other `Applications`.

`Data products` are supported by `observing systems` or other `data products`. They may also not having any supporting inputs listed. 

`Observing systems` are either supported by other `observing systems` or, most commonly, are the furthest left in the diagram without and supporting inputs listed.

**Comment by hazelshapiro** [comment]
All the links are defined by this set of attributes from the glossary: 

- Link: Defines which survey objects are connected. The rating is applied to that link.
- Criticality rating: 0-10 rating of the criticality of an input to an output, e.g. criticality of an observing system to a data product. This answers the question: On a scale of 1-10, how much would the loss of this input impact the performance of your data product or application (1 - very little impact; 10 - complete loss of performance).
- Criticality rationale: Text description answering the question: What accounts for this criticality rating? If there is a close equivalent product, why do you prefer this one?
- Performance rating: 0-100 rating of the performance of the subject. Answers the question: What is your satisfaction with this input? (0=No performance, 100 = perfect)
- Performance rationale: Text description answering the question: What accounts for this performance rating? Include any journal articles, statements or contextual observations that might help us to understand your rating.
- Gaps: If the rating is less than "ideal" what improvements are needed.
- Variable or Attribute: If an observing system or data product contains many observable properties or variables, this allows a respondent to specify which field they used.
- Rated by: Link to the respondent who provided this rating.

We may use slightly different language when directing analysts to rate the criticality of `applications` supporting `societal benefit areas` but this is a U/I or text field change, and the backend coding & implication of different criticalities (which change the line thickness) would remain the same.

**Comment by rmarow** [comment]
@hazelshapiro would you like for me to add this information to the glossary ?

**Comment by hazelshapiro** [comment]
@rmarow that would be great, thank you. Let me know on slack if you're working on that now. I'm going to add the req vs. optional information to the glossary and don't want to cross any wires

**Comment by rmarow** [comment]
@hazelshapiro take a look at the flowchart i added in this commit c5c63e036e8cb6f71ffbe50b85cf5c001796d396 and let me know if there are any changes requested.

**Comment by MattF-NSIDC** [comment]
Hey Robyn could you put the flowchart directly in the Markdown like so?

````
```mermaid
<flowchart code here>
```
````

**Comment by rmarow** [comment]
@hazelshapiro were there still edits you wanted on the flowchart in the PR related to this ticket? Happy to hop on a call to make those changes if you'd like.

**Comment by hazelshapiro** [comment]
I think the "supported by" still needs to be changed to "supports" and the data products being supported by other data products unless I just can't see those edits

**Comment by rmarow** [comment]
@hazelshapiro current state is show [here](https://github.com/nsidc/usaon-vta-docs/blob/aa002c417cd03e4d69405845deb2ab3db7180e9d/glossary.md#rated-instance-of-an-object) - that is the view were you can see the chart. [This](https://github.com/nsidc/usaon-vta-docs/pull/21/files) is the view where you can see the chart code.
