### ISSUE TITLE
UI mockups

### ISSUE THREAD

**Issue by MattF-NSIDC** [nsidc/usaon-vta-docs#4]

**Comment by rmarow** [comment]
@MattF-NSIDC do you think this story is still relevant or should it be closed as `stale`?

**Comment by MattF-NSIDC** [comment]
I agree we can close a stale. @rmarow would you mind adding a link to the mockups provided by AON?

**Comment by rmarow** [comment]
@MattF-NSIDC  https://docs.google.com/presentation/d/1TW5oS7dcM9w7Jze4Wey_TozGvwvB0IHjF4bRx8TU-O8/edit?usp=sharing this page?

**Comment by rmarow** [comment]
stale. Mockup is attached in comments and also here: https://docs.google.com/presentation/d/1TW5oS7dcM9w7Jze4Wey_TozGvwvB0IHjF4bRx8TU-O8/edit?usp=sharing
