### ISSUE TITLE
Update glossary: use `respondent` instead of expert

### ISSUE THREAD

**Issue by jwfuller** [nsidc/usaon-vta-docs#8]
I would suggest using `respondent` since it has a natural link between a `respondent` and their response. Does that make sense? As administrators, we try to make sure that the `respondents` have expertise in the things they are rating, etc. but `respondent` more accurately captures their role.

_Originally posted by @hazelshapiro in https://github.com/nsidc/usaon-vta-docs/pull/7#discussion_r1198260508_

**Comment by rmarow** [comment]
@MattF-NSIDC realizing we have also resolved this ! Closing with note that yes we are using `respondent` now.
