### ISSUE TITLE
Update glossary: two rationale fields, criticality and performance

### ISSUE THREAD

**Issue by jwfuller** [nsidc/usaon-vta-docs#9]
Should there be two rationale fields, one for criticality and one for performance?

_Originally posted by @MattF-NSIDC in https://github.com/nsidc/usaon-vta-docs/pull/7#discussion_r1187962110_

**Comment by MattF-NSIDC** [comment]
This is a documentation task, correct?

**Comment by rmarow** [comment]
This was resolved in https://github.com/nsidc/usaon-vta-docs/pull/13
